GET http://localhost:8080/index
Accept: application/json

###
http://127.0.0.1:8080/collect?v=1&tid=&cid=9c2c7cbd-633e-46eb-984e-b204c608dbb4&t=event&an=4K%20Stogram&av=4.1.2.3900/beta&ec=Subscription&ea=Add&el=Count&ev=1873&z=-38677